# Generated by Django 4.0.1 on 2022-01-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("mainapp", "0004_fill_db")]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="категория активна"),
        )
    ]
