# Generated by Django 4.0.1 on 2022-01-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("mainapp", "0005_productcategory_is_active")]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="продукт активен"),
        )
    ]
