# Generated by Django 4.0.1 on 2022-01-20 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone", models.CharField(max_length=50, verbose_name="номер телефона")),
                ("email", models.EmailField(max_length=254, verbose_name="электронная почта")),
                ("city", models.CharField(default="Москва", max_length=128, verbose_name="город")),
                ("address", models.CharField(max_length=254, verbose_name="адресс")),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, unique=True, verbose_name="имя")),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                ("is_active", models.BooleanField(default=True, verbose_name="категория активна")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="имя продукта")),
                ("image", models.ImageField(blank=True, upload_to="products_images")),
                ("short_desc", models.CharField(blank=True, max_length=60, verbose_name="краткое описание продукта")),
                ("description", models.TextField(blank=True, verbose_name="описание продукта")),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name="цена продукта")),
                ("quantity", models.PositiveIntegerField(default=0, verbose_name="количество на складе")),
                ("is_active", models.BooleanField(default=True, verbose_name="продукт активен")),
                (
                    "category",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="adminapp.productcategory"),
                ),
            ],
        ),
    ]
